crudproduct/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CartController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('category', CategoryController::class);
Route::resource('products', ProductController::class);
Route::resource('cart', CartController::class);
Route::get('saveitem/{productId}/{cartId}', [CartController::class,'saveitem']);
Route::get('delete/{productId}/{cartId}', [CartController::class,'delitem']);

crudproduct/app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    use HasFactory;
    protected $table = "cart";
    protected $primaryKey = "id";
    public $timestamps = false;
    protected $fillable = [
        'user'
    ];
    public function product_cart(){
        return $this->hasMany('App\Models\product_cart','CartId','id');
    }
    public function product(){
        return $this->belongsToMany('App\Models\product', 'product_cart', 'CartId', 'productId');
    }
}

crudproduct/app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cart;
use App\Models\Product;
use App\Models\Product_Cart;
use Illuminate\Http\Request;

class CartController extends Controller
{
    public function index()
    {
        $cart = Cart::latest()->paginate(5);

        return view('cart.index',compact('cart'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('cart.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'user' => 'required',
        ]);

        Cart::create($request->all());

        return redirect()->route('cart.index')
            ->with('success','Cart created successfully.');
    }

    public function show(Cart $cart)
    {
        $carts = $cart::with('product' )->find($cart->id);
        $product = Product::all();
        return view('cart.addproduct',compact('carts','product'));
    }


    public function edit(Cart $cart)
    {
        return view('cart.edit',compact('cart'));
    }


    public function update(Request $request, Cart $cart)
    {
        $request->validate([
            'user' => 'required',
        ]);

        $cart->update($request->all());

        return redirect()->route('cart.index')
            ->with('success','Cart updated successfully');
    }


    public function destroy(Cart $cart)
    {
        $cart->delete();
        return redirect()->route('cart.index')
            ->with('success','Cart deleted successfully');
    }
    public function saveitem($productId,$cartId){
       if(Product_Cart::where('cartId',$cartId)->where('productId',$productId)->count() == 0){
           Product_Cart::create([
               'cartId'=>$cartId,
               'productId'=>$productId,
           ]);
       };
        return redirect()->back();
    }
    public function delitem($productId,$cartId){
        Product_Cart::where('cartId',$cartId)->where('productId',$productId)->delete();
        return redirect()->back();
    }
}

crudproduct/resources/views/Cart/addproduct.blade.php
@extends('Layout.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>User : {{$carts->user}}</h2>
            </div>

        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($carts->product as $value)
            <tr>
                <td>{{ $value->name }}</td>
                <td>{{ $value->detail }}</td>
                <td>
                    <a class="btn btn-danger" href="{{ Url('/')}}/delete/{{$value->id}}/{{$carts->id}}">Delete</a>
                </td>
            </tr>
        @endforeach
    </table>
    <h4>All Product</h4>
    <table class="table table-bordered">
        <tr>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($product as $value)
            <tr>
                <td>{{ $value->name }}</td>
                <td>{{ $value->detail }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ Url('/')}}/saveitem/{{$value->id}}/{{$carts->id}}">Add to Cart</a>
                </td>
            </tr>
        @endforeach
    </table>



@endsection

crudproduct/resources/views/Cart/create.blade.php
@extends('Layout.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Cart</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('cart.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('create'))
        <div class="alert alert-warning ">
            <p>{{ $message }}</p>
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('cart.store') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>User:</strong>
                    <input type="text" name="user" class="form-control" placeholder="User">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

crudproduct/resources/views/Cart/edit.blade.php
@extends('Layout.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Cart</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('cart.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('cart.update',$cart->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>User:</strong>
                    <input type="text" name="user" value="{{ $cart->user }}" class="form-control" placeholder="User">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

crudproduct/resources/views/Cart/index.blade.php
@extends('Layout.layout')

@section('content')

    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>CRUD CART</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('cart.create') }}"> Create New Cart</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>User</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($cart as $value)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $value->user }}</td>
                <td>
                    <form action="{{ route('cart.destroy',$value->id) }}" method="POST">

                        <a class="btn btn-info" href="{{ route('cart.show',$value->id) }}">Add Product</a>

                        <a class="btn btn-primary" href="{{ route('cart.edit',$value->id) }}">Edit</a>

                        @csrf
                        @method('DELETE')

                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>

    {!! $cart->links() !!}

@endsection